### ISSUE TITLE
[FR] Add "both" option so Inbox folder and note are not mutually exclusive 

### ISSUE THREAD

**Issue by FeralFlora** [Zachatoo/obsidian-inbox#12]
I think it's great that the latest update added support for an inbox folder. However, I don't want to give up the inbox note I have for quick thoughts that don't necessarily warrant a full note. Therefore, I think inbox folder and inbox note shouldn't be mutually exclusive, e.g., there should be a third “both” option.

**Comment by Zachatoo** [comment]
Interesting, I hadn't thought of this use case.

Instead of supporting a "both" option, I wonder if it makes more sense to allow configuring multiple inboxes. I was thinking of something similar to how the folder templates feature is implemented for the Templater plugin. You could have two inboxes, one setup for a note and one setup for a folder. This would also support if you wanted to have multiple inbox notes or multiple inbox folders.

<img width="790" alt="image" src="https://github.com/Zachatoo/obsidian-inbox/assets/6936914/f788429f-90b6-47c3-b21b-7ee00e932f98">

**Comment by FeralFlora** [comment]
That sounds like a good solution!

**Comment by ized3d** [comment]
I'd love to have several Inbox options as I want to physically separate between stuff that I have to do at work from Life<tm> stuff. Both inboxes needs to be processed, but at (very) separate times. Reduces my clutter :)

**Comment by Zachatoo** [comment]
Added in version 3.0.0!

This ended up being a bigger change than I anticipated. Please let me know if your settings don't migrate over smoothly.
