### ISSUE TITLE
[BUG] False inbox notifications when there are actually no external changes.

### ISSUE THREAD

**Issue by FeralFlora** [Zachatoo/obsidian-inbox#3]
I repeatedly get notifications about changes to my inbox note, even though no actual changes have been made.

Am I supposed to add all the current content of the note Inbox base contents box to stop this from occurring?

Without these false positives, it will be a very useful plugin!

**Comment by Zachatoo** [comment]
What I recommend is setting up your inbox note as it would look like in it's "blank" state, as in, what the note will look like if there is nothing to process in the note. Then use the "Set inbox note" command to set the note and the path and base contents for the inbox note. Then you should only get a notification if the contents of your inbox note do not match it's "blank" state.

**Comment by Zachatoo** [comment]
I went ahead and added a walkthrough feature to this plugin, if you update to version 0.1.0 you'll find a walkthrough button in the plugin's settings, it should help you get set up and help future users know how to get this plugin working.

Let me know if the walkthrough isn't clear, or if you have further questions!

**Comment by FeralFlora** [comment]
Thanks for the response.

It's not exactly clear to me what you mean by "setting up your inbox note as it would look like in it's "blank" state".

Do you mean that the plugin gives notifications as long as the inbox note doesn't match the "blank slate"? And in that case, will the plugin keep giving notifications, so long as the note has content beyond the blank slate? 

I thought it would work more like email, that you get notified about new emails, but not old unread emails. In this case, what's considered a blank slate would update after each notification to include the newly added content.

Another problem is that I have an existing inbox note with captured content in it already, it's not blank. How do I set up in my case? Or do I have to empty out the inbox file first?

Also, the *Set inbox note* command is not showing up in the command palette. I have updated to version 0.1.0, and I can see the command under Hotkeys, but it doesn't show up in the command palette for some reason. Regardless, I had already set up the note location from the settings page, so the setup was not the problem. The problem is a mismatch of my expectations and the actual behavior.

I also followed the walkthrough and used a keyboard shortcut to use the command. It worked in the sense that no notification was given upon restart after the setup. But, like I suspected, after adding a line, I get notifications every time I open Obsidian. I take it that this is by design, but at least for me, it would be more sensible if there was only one notification per change. Perhaps this alternative behavior could be a setting to serve more use-cases?

**Comment by Zachatoo** [comment]
That's odd that the "Set inbox note" command isn't showing up, it shows up for me when my cursor is actively in my inbox note. I can investigate that further.

You are right that by design, this plugin was intended to show a notification any time there was content in your inbox note that wasn't expected.

I do think it is a good idea to have a setting that only shows a notification if there is _new_ content. Though we will need to define what new means. If you opened Obsidian, edited the inbox note, then restarted Obsidian, would you expect to get a notification? Or would you only expect to get a notification if the note was modified outside of Obsidian, for example if you closed Obsidian, edited a note with another program, then opened Obsidian you would get a notification?

**Comment by FeralFlora** [comment]
Yeah, I don't know why the command is missing, could be something on my end.

It would be great if that setting were added!

>If you opened Obsidian, edited the inbox note, then restarted Obsidian, would you expect to get a notification? Or would you only expect to get a notification if the note was modified outside of Obsidian, for example if you closed Obsidian, edited a note with another program, then opened Obsidian you would get a notification?

My expectations were that it would behave as in the latter case.

**Comment by Zachatoo** [comment]
I have added this as a setting in version 0.2.0, and the way you're expecting it to work will be the default setting, since I'm expecting most users of this plugin to expect it to work the way you're expecting it to. Walkthrough is also updated.

Let me know if the latest update works well for you or not!

I still have not been able to reproduce the bug you found where the "Set inbox note" command doesn't show up with your cursor in a markdown note in edit mode.

**Comment by FeralFlora** [comment]
That's great man, I really appreciate the effort and responsiveness! 

I haven't had a chance to check it out yet, but I will report back tomorrow.

**Comment by FeralFlora** [comment]
I have tested the update now, and it works great and as expected! I think the walkthrough is very clear and helpful too, and the two settings are explained well.

I figured out that the reason the set inbox note command wasn't showing up was because I was viewing the note in reading mode. The command is only visible if I prompt it in editing mode.

**Comment by Zachatoo** [comment]
Awesome! Wanna mark this as closed if everything has been resolved?

I will make a note to include in the walkthrough that your note needs to be in editing mode and focused on order for the "set inbox note" command to show, or I'll find a workaround.
